import sys
from types import SimpleNamespace

import pytest

from app.article_ingest import _clamp_label
from app.sources import PAGE_FETCH_CONFIGS
from app.constants import MIN_PERSIST_CONFIDENCE, NO_KEYWORDS_CONFIDENCE
from app.ticker_extraction import (
    _extract_article_body,
    _build_symbol_keywords,
    _extract_entry_tickers,
    _extract_source_fallback_tickers,
    _extract_table_cell_symbols_from_html,
    _fetch_source_page_html,
    _is_businesswire_article_url,
    _is_source_article_url,
    _should_persist_entry,
    _source_page_cache,
)
@pytest.fixture()
def clean_page_cache():
    _source_page_cache.clear()
    yield
    _source_page_cache.clear()

def test_build_symbol_keywords_extracts_distinctive_words():
    rows = [
        (1, "CGO", "Calamos Global Total Return", "Calamos Advisors LLC"),
        (2, "PMO", "Putnam Muni Opportunities", "Franklin Advisers, Inc."),
        (3, "CMU", "MFS High Yield Municipal", "MFS"),
        (4, "CFND", "C1 Fund Inc.", "C1 Advisors LLC"),
        (5, "DNP", "DNP Select Income", "Duff & Phelps Inv Mgmt Co (IL)"),
        (
            6,
            "EDF",
            "Virtus Stone Harbor Emerging Markets Inc",
            "Virtus Investment Advisors (VIA)",
        ),
    ]
    kws = _build_symbol_keywords(rows)
    assert "calamos" in kws["CGO"]
    assert "calamos global" in kws["CGO"]
    assert "putnam" in kws["PMO"]
    assert "putnam muni" in kws["PMO"]
    assert "franklin" not in kws["PMO"]
    assert "mfs" in kws["CMU"]
    assert "mfs high" in kws["CMU"]
    assert "high" not in kws["CMU"]
    assert "yield" not in kws["CMU"]
    assert "municipal" not in kws["CMU"]
    assert "c1" in kws["CFND"]
    assert "il" not in kws["DNP"]
    assert "via" not in kws["EDF"]
    # Generic words should be excluded
    assert "fund" not in kws.get("CGO", frozenset())
    assert "trust" not in kws.get("CGO", frozenset())
    assert "llc" not in kws.get("CGO", frozenset())
    assert "inc" not in kws.get("PMO", frozenset())

def test_sponsor_brand_phrase_generated_for_first_trust():
    kws = _build_symbol_keywords(
        [(1, "FFA", "First Trust Enhanced Equity Income", "First Trust Advisors L.P.")]
    )

    assert "first trust" in kws["FFA"]

def test_sponsor_brand_phrase_not_generated_for_short_overlap():
    kws = _build_symbol_keywords(
        [(1, "NIM", "Nuveen Select Maturity Muni", "Nuveen Fund Advisors, LLC.")]
    )

    assert "nuveen fund" not in kws["NIM"]

def test_keywordless_fund_can_use_two_word_sponsor_phrase():
    kws = _build_symbol_keywords(
        [(1, "PCF", "High Income Securities", "Bulldog Investors LLP")]
    )

    assert kws["PCF"] == frozenset({"bulldog investors"})

def test_validation_keywords_override_replaces_autogenerated():
    kws = _build_symbol_keywords(
        [(1, "FFA", "First Trust Enhanced Equity Income", "First Trust Advisors L.P.", "brand phrase, custom")]
    )

    assert kws["FFA"] == frozenset({"brand phrase", "custom"})

def test_token_match_validated_when_fund_name_present():
    known = {"CGO"}
    sym_kws = {"CGO": frozenset({"calamos", "calamos global"})}
    hits = _extract_entry_tickers(
        "Calamos Global Total Return CGO declares distribution",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "CGO" in hits
    assert hits["CGO"][0] == "validated_token"
    assert hits["CGO"][1] == 0.68

def test_token_match_not_validated_without_fund_name():
    known = {"CGO"}
    sym_kws = {"CGO": frozenset({"calamos", "calamos global"})}
    hits = _extract_entry_tickers(
        "Envestnet appoints new CGO to lead growth strategy",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "CGO" in hits
    assert hits["CGO"][0] == "token"
    assert hits["CGO"][1] == 0.62

def test_token_match_not_validated_with_sponsor_brand_only_context():
    known = {"CGO"}
    sym_kws = {"CGO": frozenset({"calamos", "calamos global"})}
    hits = _extract_entry_tickers(
        "Calamos appoints new CGO",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "CGO" in hits
    assert hits["CGO"][0] == "token"
    assert hits["CGO"][1] == 0.62

def test_paren_match_requires_fund_name_validation():
    known = {"CGO"}
    sym_kws = {"CGO": frozenset({"calamos", "calamos global"})}
    hits = _extract_entry_tickers(
        "Fund update for (CGO) distribution schedule",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "CGO" in hits
    assert hits["CGO"][0] == "paren"
    assert hits["CGO"][1] == 0.62

def test_paren_match_keeps_explicit_symbol_when_keywords_missing():
    known = {"CGO"}
    sym_kws = {"CGO": frozenset()}
    hits = _extract_entry_tickers(
        "Fund update for (CGO) distribution schedule",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "CGO" in hits
    assert hits["CGO"][0] == "paren"
    assert hits["CGO"][1] == NO_KEYWORDS_CONFIDENCE

def test_exchange_match_bypasses_fund_name_validation():
    known = {"CGO"}
    sym_kws = {"CGO": frozenset({"calamos", "calamos global"})}
    hits = _extract_entry_tickers(
        "NYSE: CGO distribution declared",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "CGO" in hits
    assert hits["CGO"][0] == "exchange"
    assert hits["CGO"][1] == 0.88

def test_generic_fund_words_do_not_validate_plain_token_match():
    known = {"CMU"}
    sym_kws = _build_symbol_keywords(
        [(1, "CMU", "MFS High Yield Municipal", "MFS")]
    )
    hits = _extract_entry_tickers(
        "Company expands high yield municipal CMU platform",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "CMU" in hits
    assert hits["CMU"][0] == "token"
    assert hits["CMU"][1] < MIN_PERSIST_CONFIDENCE

def test_token_match_validated_when_short_sponsor_acronym_present():
    known = {"CMU"}
    sym_kws = _build_symbol_keywords(
        [(1, "CMU", "MFS High Yield Municipal", "MFS")]
    )
    hits = _extract_entry_tickers(
        "MFS High Yield Municipal CMU declares distribution",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "CMU" in hits
    assert hits["CMU"][0] == "validated_token"
    assert hits["CMU"][1] >= MIN_PERSIST_CONFIDENCE

def test_distribution_words_still_validate_normal_feed_title_match():
    known = {"PDT"}
    sym_kws = _build_symbol_keywords(
        [
            (
                1,
                "PDT",
                "JHancock Premium Dividend Fund",
                "John Hancock",
            )
        ]
    )
    hits = _extract_entry_tickers(
        "Premium Dividend Fund PDT declares monthly distribution",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "premium dividend" in sym_kws["PDT"]
    assert "PDT" in hits
    assert hits["PDT"][0] == "validated_token"
    assert hits["PDT"][1] >= MIN_PERSIST_CONFIDENCE

def test_short_keyword_validation_respects_word_boundaries():
    known = {"DNP"}
    sym_kws = {"DNP": frozenset({"il"})}
    hits = _extract_entry_tickers(
        "Company will appoint new DNP leader",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "DNP" in hits
    assert hits["DNP"][0] == "token"
    assert hits["DNP"][1] == 0.62

def test_two_letter_sponsor_keyword_does_not_validate_location_suffix():
    known = {"DNP"}
    sym_kws = _build_symbol_keywords(
        [(1, "DNP", "DNP Select Income", "Duff & Phelps Inv Mgmt Co (IL)")]
    )
    hits = _extract_entry_tickers(
        "Chicago, IL office names new DNP executive",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "DNP" in hits
    assert hits["DNP"][0] == "token"
    assert hits["DNP"][1] < MIN_PERSIST_CONFIDENCE

def test_trailing_three_letter_sponsor_acronym_does_not_validate_token_match():
    known = {"EDF"}
    sym_kws = _build_symbol_keywords(
        [
            (
                1,
                "EDF",
                "Virtus Stone Harbor Emerging Markets Inc",
                "Virtus Investment Advisors (VIA)",
            )
        ]
    )
    hits = _extract_entry_tickers(
        "Company comments via EDF filing update",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "EDF" in hits
    assert hits["EDF"][0] == "token"
    assert hits["EDF"][1] < MIN_PERSIST_CONFIDENCE

def test_false_positive_articles_filtered_end_to_end():
    """Simulate the user's reported false positives -- token-only matches should not persist."""
    known = {"CGO", "PMO", "FT", "FRA", "SPE", "CEE"}
    sym_kws = {
        "CGO": frozenset({"calamos", "calamos global"}),
        "PMO": frozenset({"putnam", "putnam muni"}),
        "FT": frozenset({"franklin", "franklin universal"}),
        "FRA": frozenset({"blackrock", "blackrock floating"}),
        "SPE": frozenset({"bulldog", "special"}),
        "CEE": frozenset({"central", "eastern", "europe"}),
    }

    cases = [
        (
            "Envestnet Accelerates Adaptive WealthTech Innovation",
            "New CGO appointment announced",
        ),
        ("Mace Consult Launches as Standalone PMO Company", ""),
        ("Sokin Appoints Former FT Partners VP Tom Steer as CFO", ""),
        (
            "Vior Gold Corporation Announces District Scale Projects Acquisition",
            "Listed on FRA exchange",
        ),
    ]

    for title, summary in cases:
        hits = _extract_entry_tickers(
            title, summary, "https://example.com", "", known, symbol_keywords=sym_kws
        )
        # All matches should be unvalidated tokens (0.62) — below persist threshold
        for sym, (match_type, confidence) in hits.items():
            assert (
                confidence < MIN_PERSIST_CONFIDENCE
            ), f"False positive: {sym} in '{title}' has confidence {confidence} ({match_type})"

@pytest.mark.parametrize(
    ("row", "title", "summary"),
    [
        (
            (1, "TEI", "Templeton Emerg Mkts Income", "Franklin Advisers, Inc."),
            "Bloomberg Tax Showcases Industry-Leading AI-Powered Tools at TEI Midyear 2026",
            "Bloomberg Tax announces its continuing Platinum sponsorship of the Tax Executives Institute (TEI) 2026 Midyear Conference.",
        ),
        (
            (2, "NIM", "Nuveen Select Maturity Muni", "Nuveen Fund Advisors, LLC."),
            "Gold Coast Federal Credit Union Selects Algebrik to Modernize Lending",
            "The platform is designed to improve net interest margins (NIM) across lending operations.",
        ),
        (
            (3, "ECC", "Eagle Point Credit Company LLC", "Eagle Point Credit Management"),
            "Cypherpunk Makes $5M Investment into Zcash Open Development Lab (ZODL)",
            "Cypherpunk said the investment supports Electric Coin Company (ECC) ecosystem development.",
        ),
        (
            (4, "CET", "Central Securities Corporation", "Central Securities Corp"),
            "Atos launches new modernization initiative",
            "The company said its central enterprise transformation (CET) program will accelerate delivery.",
        ),
    ],
)
def test_real_world_paren_false_positives_stay_subthreshold(row, title, summary):
    symbol = row[1]
    known = {symbol}
    sym_kws = _build_symbol_keywords([row])

    hits = _extract_entry_tickers(
        title,
        summary,
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )

    assert symbol in hits
    assert hits[symbol][1] < MIN_PERSIST_CONFIDENCE

def test_real_cef_article_persists_end_to_end():
    """A real CEF article with fund name context should persist."""
    known = {"CGO"}
    sym_kws = {"CGO": frozenset({"calamos", "calamos global"})}

    hits = _extract_entry_tickers(
        "Calamos Global Total Return Fund CGO Declares Monthly Distribution",
        "",
        "https://example.com",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "CGO" in hits
    assert hits["CGO"][1] >= MIN_PERSIST_CONFIDENCE
    assert _should_persist_entry("prnewswire", hits) is True

def test_paren_stopword_ticker_blocked_without_fund_name():
    """(USA) in an Occidental press release should NOT match."""
    known = {"USA"}
    sym_kws = {"USA": frozenset({"liberty", "all-star", "equity"})}
    hits = _extract_entry_tickers(
        "Occidental Announces Tender Offers (USA)",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "USA" not in hits

def test_paren_stopword_ticker_allowed_with_fund_name():
    """(USA) in a Liberty All-Star article SHOULD match."""
    known = {"USA"}
    sym_kws = {"USA": frozenset({"liberty", "all-star", "equity"})}
    hits = _extract_entry_tickers(
        "Liberty All-Star Equity Fund (USA) Declares Distribution",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "USA" in hits
    assert hits["USA"][0] == "paren"
    assert hits["USA"][1] == 0.75

def test_ffa_validated_by_first_trust_phrase():
    known = {"FFA"}
    sym_kws = _build_symbol_keywords(
        [(1, "FFA", "First Trust Enhanced Equity Income", "First Trust Advisors L.P.")]
    )

    hits = _extract_entry_tickers(
        "First Trust declares quarterly distribution for FFA",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )

    assert hits["FFA"] == ("validated_token", 0.68)

def test_empty_keyword_symbol_gets_reduced_confidence():
    hits = _extract_entry_tickers(
        "Fund update for (CGO) distribution schedule",
        "",
        "https://example.com/story",
        "",
        {"CGO"},
        symbol_keywords={"CGO": frozenset()},
    )

    assert hits["CGO"] == ("paren", NO_KEYWORDS_CONFIDENCE)

def test_no_keywords_confidence_still_persists():
    assert NO_KEYWORDS_CONFIDENCE >= MIN_PERSIST_CONFIDENCE

def test_first_trust_ffa_not_validated_by_common_word_first():
    """'first' is too generic to validate FFA token matches."""
    known = {"FFA"}
    sym_kws = _build_symbol_keywords(
        [(1, "FFA", "First Trust Enhanced Equity Income", "First Trust Advisors L.P.")]
    )
    assert "first trust" in sym_kws["FFA"]

    hits = _extract_entry_tickers(
        "FFA members held their first annual meeting",
        "",
        "https://example.com/story",
        "",
        known,
        symbol_keywords=sym_kws,
    )
    assert "FFA" in hits
    assert hits["FFA"][0] == "token"
    assert hits["FFA"][1] < MIN_PERSIST_CONFIDENCE
