apiVersion: 1
prune: true

deleteDatasources:
  - name: Postgres
    orgId: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
  - name: Postgres
    orgId: 1
    uid: postgres
    type: postgres
    access: proxy
    url: db:5432
    user: $POSTGRES_USER
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: $POSTGRES_PASSWORD
    editable: true
